import { UpdatedProformaInvoiceResponse } from '../models/UpdatedProformaInvoiceResponse';
import { UpdatedFactureResponse, FactureResponse } from '../models/UpdatedFactureResponse';
import { LigneFactureResponse } from '../models/LigneFactureResponse';
import { LigneDevisResponse } from '../models/LigneDevisResponse';

/**
 * Maps an UpdatedProformaInvoiceResponse to an UpdatedFactureResponse
 * Used when converting a validated Proforma into a final Invoice.
 */
export const mapProformaToFacture = (proforma: UpdatedProformaInvoiceResponse): UpdatedFactureResponse => {
  
  // Map line items from Proforma to Facture format
  const lignesFacture: LigneFactureResponse[] = (proforma.lignesDevis || []).map((ligne: LigneDevisResponse) => ({
    idLigne: ligne.idLigne,
    idProduit: ligne.idProduit,
    nomProduit: ligne.nomProduit,
    quantite: ligne.quantite,
    prixUnitaire: ligne.prixUnitaire,
    montantTotal: ligne.montantTotal,
    description: ligne.description,
    remisePourcentage: ligne.remisePourcentage,
    remiseMontant: ligne.remiseMontant,
    isTaxLine: ligne.isTaxLine,
    debit: ligne.debit,
    credit: ligne.credit,
  }));

  return {
    // Basic Info
    idFacture: undefined, // New ID will be generated by the backend
    numeroFacture: undefined, // Will be generated following invoice numbering sequence
    dateFacturation: new Date().toISOString().split('T')[0],
    dateSysteme: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    
    // Status & Type
    etat: FactureResponse.etat.BROUILLON, // Always starts as a draft
    type: proforma.type || "VENTE",
    
    // Client Info
    idClient: proforma.idClient,
    nomClient: proforma.nomClient,
    adresseClient: proforma.adresseClient,
    emailClient: proforma.emailClient,
    telephoneClient: proforma.telephoneClient,
    referalClientId: proforma.referalClientId,

    // Financials
    montantHT: proforma.montantHT,
    montantTVA: proforma.montantTVA,
    montantTTC: proforma.montantTTC,
    montantTotal: proforma.montantTotal,
    finalAmount: proforma.finalAmount,
    montantRestant: proforma.finalAmount, // Initially, the full amount is remaining
    
    // Discounts & VAT
    remiseGlobalePourcentage: proforma.remiseGlobalePourcentage,
    remiseGlobaleMontant: proforma.remiseGlobaleMontant,
    applyVat: proforma.applyVat,
    
    // Localization & Terms
    devise: proforma.devise || "XAF",
    tauxChange: proforma.tauxChange || 1,
    modeReglement: proforma.modeReglement as unknown as FactureResponse.modeReglement,
    conditionsPaiement: proforma.conditionsPaiement,
    nbreEcheance: proforma.nbreEcheance || 1,
    
    // References
    nosRef: proforma.nosRef,
    vosRef: proforma.vosRef,
    idDevisOrigine: proforma.idProformaInvoice, // Keep track of the source proforma
    
    // Content
    lignesFacture: lignesFacture,
    notes: proforma.notes,
    
    // Metadata
    envoyeParEmail: false,
  };
};


import { UpdatedSalesOrderResponse,SalesOrderResponse } from '../models/UpdatedSalesOrder';

/**
 * Transforms a Proforma Invoice into a Sales Order.
 * Primarily used when a client accepts a Proforma and the process moves to fulfillment.
 */
export const mapProformaToSalesOrder = (proforma: UpdatedProformaInvoiceResponse): UpdatedSalesOrderResponse => {
  const now = new Date().toISOString();

  return {
    // New Order Identifiers
    idSalesOrder: undefined, // Backend generated
    numeroSalesOrder: undefined, // Backend generated

    // Dates
    dateCreation: now,
    dateSysteme: now,
    expectedDeliveryDate: undefined, // To be filled by logistics
    deliveryDate: undefined,

    // Initial Status
    statut: SalesOrderResponse.statut.BROUILLON,

    // Client Info Mapping
    idClient: proforma.idClient,
    nomClient: proforma.nomClient,
    adresseClient: proforma.adresseClient,
    emailClient: proforma.emailClient,
    telephoneClient: proforma.telephoneClient,

    // Recipient Defaults (Default to Client Info)
    recipientName: proforma.nomClient,
    recipientPhone: proforma.telephoneClient,
    recipientAddress: proforma.adresseClient,
    recipientCity: undefined,

    // Source Reference (Tracing)
    idDevisOrigine: proforma.idProformaInvoice,
    numeroDevisOrigine: proforma.numeroProformaInvoice,

    // Line Items (LigneDevisResponse is compatible with SO lines)
    lignesSalesOrder: proforma.lignesDevis ? [...proforma.lignesDevis] : [],

    // Financial Summary
    montantHT: proforma.montantHT,
    montantTVA: proforma.montantTVA,
    montantTTC: proforma.montantTTC,
    devise: proforma.devise || 'XAF',
    applyVat: proforma.applyVat,

    // Logistics & Metadata
    transportMethod: undefined,
    idAgency: undefined,
    agencyInfo: undefined,
    
    // Payment Mapping (Handles potential enum differences safely)
    modeReglement: proforma.modeReglement as unknown as SalesOrderResponse.modeReglement,
    
    nosRef: proforma.nosRef,
    vosRef: proforma.vosRef,
    notes: proforma.notes,
    createdAt: now,
    updatedAt: now,
  };
};