
import { UpdatedDevisResponse } from "../models/UpdatedDevisResponse";
import { UpdatedSalesOrderResponse } from "../models/UpdatedSalesOrder";
import { SalesOrderResponse } from "../models/UpdatedSalesOrder";
export const transformDevisToSalesOrder = (devis: UpdatedDevisResponse): UpdatedSalesOrderResponse => {
    const now = new Date().toISOString();

    return {
        // We generate a temporary ID or leave it for the backend, 
        // but we definitely link the source quotation.
        
        
        // Dates
        dateCreation: now.split('T')[0],
        dateSysteme: now,
        // Default delivery is usually set to +3 days from now
        expectedDeliveryDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],

        // Status: Starts as Draft or Validated depending on your workflow
        statut: SalesOrderResponse.statut.BROUILLON,

        // Client Info (Copied directly)
        idClient: devis.idClient,
        nomClient: devis.nomClient,
        adresseClient: devis.adresseClient,
        emailClient: devis.emailClient,
        telephoneClient: devis.telephoneClient,

        // Recipient Info: Default to Client info, can be edited later in the UI
        recipientName: devis.nomClient,
        recipientPhone: devis.telephoneClient,
        recipientAddress: devis.adresseClient,

        // Reference to source Quotation (Crucial for tracking)
        idDevisOrigine: devis.idDevis,
        numeroDevisOrigine: devis.numeroDevis,

        // Line Items: Map Devis lines to Sales Order lines
        lignesSalesOrder: devis.lignesDevis || [],

        // Financial Summary
        montantHT: devis.montantHT,
        montantTVA: devis.montantTVA,
        montantTTC: devis.montantTTC,
        devise: devis.devise || 'XAF',

        // Logistics Defaults
        transportMethod: SalesOrderResponse.transportMethod.RETRAIT_MAGASIN,
        
        // Payment Info (Cast to SalesOrder version of enum)
        modeReglement: devis.modeReglement as unknown as SalesOrderResponse.modeReglement,

        // Additional Fields
        applyVat: devis.applyVat,
        nosRef: devis.numeroDevis, // Use the Devis number as internal ref
        vosRef: devis.vosRef,
        notes: devis.notes,

        // Metadata
        createdAt: now,
        updatedAt: now
    };
};




import { DeliveryNoteLineResponse,DeliveryNoteResponse } from "../models/DeliveryNoteResponse";
/**
 * Transforms an UpdatedSalesOrderResponse into a DeliveryNoteResponse.
 * This is used when an order is ready to be dispatched/delivered.
 */
export const mapSalesOrderToDeliveryNote = (order: UpdatedSalesOrderResponse): DeliveryNoteResponse => {
  const now = new Date().toISOString();

  // Map Sales Order lines to Delivery Note lines
  const lines: DeliveryNoteLineResponse[] = (order.lignesSalesOrder || []).map((ligne) => ({
    productId: ligne.idProduit,
    idProduit: ligne.idProduit, // Maintain both for compatibility
    description: ligne.description || ligne.nomProduit,
    quantity: ligne.quantite,
    unitPrice: ligne.prixUnitaire,
    amount: ligne.montantTotal,
  }));

  return {
    // Basic Identifiers (New DN ID usually generated by backend)
    idDN: undefined,
    deliveryNoteNumber: undefined, 

    // Status Initialization
    etat: DeliveryNoteResponse.etat.BROUILLON,

    // Client Info (The payer)
    idClient: order.idClient,
    nomClient: order.nomClient,
    adresseClient: order.adresseClient,
    emailClient: order.emailClient,
    telephoneClient: order.telephoneClient,

    // Recipient Info (The delivery destination)
    recipientName: order.recipientName,
    recipientPhone: order.recipientPhone,
    recipientAddress: order.recipientAddress,
    recipientCity: order.recipientCity,

    // Logistics Information
    deliveryAgency: order.agencyInfo?.name || order.idAgency,
    deliveryDate: order.deliveryDate || order.expectedDeliveryDate || now,
    dueDate: order.expectedDeliveryDate,

    // Line Items
    lines: lines,

    // Financial Totals
    totalAmount: order.montantTTC,

    // Tracing / References
    idSaleOrder: order.idSalesOrder,
    SaleOrderNumber: order.numeroSalesOrder,

    // Metadata
    termsAndConditions: "Goods remain the property of the seller until full payment is received.",
    createdAt: now,
    updatedAt: now,
  };
};



import { FactureResponse,} from "../models/FactureResponse";
import { UpdatedFactureResponse } from "../models/UpdatedFactureResponse";
import { LigneFactureResponse } from "../models/LigneFactureResponse";

/**
 * Transforms a Sales Order into a Client Invoice (Facture)
 * Use case: When an order is validated or delivered and needs to be billed.
 */
export const mapSalesOrderToFacture = (order: UpdatedSalesOrderResponse): UpdatedFactureResponse => {
    
    // 1. Map Sales Order Line Items to Invoice Line Items
    const lignesFacture: LigneFactureResponse[] = (order.lignesSalesOrder || []).map((ligne) => ({
        idProduit: ligne.idProduit,
        nomProduit: ligne.nomProduit,
        quantite: ligne.quantite,
        prixUnitaire: ligne.prixUnitaire,
        montantTotal: ligne.montantTotal,
        description: ligne.description || '',
        remisePourcentage: 0, // Default to 0 unless logic exists in Order
        isTaxLine: false
    }));

    // 2. Map Payment Modes (Matching Enums)
    const mapModeReglement = (mode?: SalesOrderResponse.modeReglement): FactureResponse.modeReglement => {
        switch (mode) {
            case SalesOrderResponse.modeReglement.VIREMENT: return FactureResponse.modeReglement.VIREMENT;
            case SalesOrderResponse.modeReglement.ESPECES: return FactureResponse.modeReglement.ESPECES;
            case SalesOrderResponse.modeReglement.CHEQUE: return FactureResponse.modeReglement.CHEQUE;
            default: return FactureResponse.modeReglement.AUTRE;
        }
    };

    // 3. Set Invoice Status based on Order Status
    // Usually, transforming an order creates a 'BROUILLON' (Draft) invoice
    const initialEtat = order.statut === SalesOrderResponse.statut.LIVRE 
        ? FactureResponse.etat.ENVOYE 
        : FactureResponse.etat.BROUILLON;

    return {
        // Metadata
        dateFacturation: new Date().toISOString().split('T')[0], // Today's date
        dateSysteme: new Date().toISOString(),
        etat: initialEtat as FactureResponse.etat,
        type: "VENTE",

        // Client Info
        idClient: order.idClient,
        nomClient: order.nomClient,
        adresseClient: order.adresseClient,
        emailClient: order.emailClient,
        telephoneClient: order.telephoneClient,

        // Financials
        montantHT: order.montantHT,
        montantTVA: order.montantTVA,
        montantTTC: order.montantTTC,
        montantTotal: order.montantTTC, // Initially total is TTC
        montantRestant: order.montantTTC, // Nothing paid yet
        finalAmount: order.montantTTC,
        
        applyVat: order.applyVat ?? (order.montantTVA ? order.montantTVA > 0 : false),
        devise: order.devise || "XAF",
        tauxChange: 1,

        // References
        nosRef: order.nosRef,
        vosRef: order.vosRef,
        referenceCommande: order.numeroSalesOrder, // Order # becomes the reference
        idDevisOrigine: order.idDevisOrigine,
        
        // Items
        lignesFacture: lignesFacture,

        // Payment
        modeReglement: mapModeReglement(order.modeReglement),
        
        notes: order.notes,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    };
};